### PR TITLE
Reopen #24: using a .env file to deliver credential token to bot.py

### PR DESCRIPTION
**Pull request by Asterisk007**
Bringing up an old issue: https://github.com/CodeMastr3/hackbot/pull/24

This again changes the workflow, but nothing too exciting. Here's what has to be done:
1. Create file `token_giver.py` inside the same directory as this project.
2. Inside it, place this code:
```python
def get_token():
    return "<bot token string>"
```

### CODE REVIEW

**Comment by Ramsfield** [comment]
This alters the workflow of the bot and changes nothing.

The current workflow is exactly the same where we have `token.py` and the function name is `stringToken()`

Eventual rework should be more towards  @ramcguire 's suggestions seen here https://github.com/CodeMastr3/hackbot/pull/24
Especially since it's inline with what the README currently says.

**Comment by Asterisk007** [comment]
Can we reopen this? I've uncommented the lines relevant to the changes made to allow for a `.env` file.

**Comment by Ramsfield** [comment]
Yeah it's no worries. Could also start a new pr. Either way is fine

**Comment by Ramsfield** [comment]
Assigning this to me. Going to set up bot to allow this update. Need to get @CodeMastr3's approval, then i'll merge

**Comment by Asterisk007** [comment]
Neato.

**Comment by CodeMastr3** [comment]
I didn't get the email about this but assuming this doesn't break PR #48 merging this should be fine

**Comment by Asterisk007** [comment]
@CodeMastr3 It hasn't been merged with those changes, so yours would need to be pulled first.

**Comment by Asterisk007** [comment]
I'm closing this PR for now until the master branch gets updated with #48. Opening a new PR on the test branch.

**Pull request closed without merging**
