### PR TITLE
Updates the Roles commands ['add', 'sub']

### PR DESCRIPTION
**Pull request by Ramsfield**
Previously, upon attempting to add or subtract roles, a user would be greeted with a general message of "I've succeeded" or "I've failed"

Now it will check each role as it performs the appropriate function to it and will tell the user if the action succeeded or failed (because they had/didn't have the role or because the role doesn't exist)
example

### CODE REVIEW

**Comment by ydoco** [comment]
wow cool commit!

**Comment by ydoco** [comment]
I knew your name was steve!

**Comment by Ramsfield** [comment]
> I knew your name was steve!

You caught the tater!

**Comment by Ramsfield** [comment]
With a new semester starting tomorrow, I'm going to merge it now. If you have any concerns from it, please let me know and we can fix it.

**Pull request merged**
