### PR TITLE
Automatically detect stock tickers in messages and display their current prices

### PR DESCRIPTION
**Pull request by Noxium**
Scans each message for the presence of a stock ticker in the format of `$<ticker>`, such as `$gme` or `$aapl`. The bot replies with the current price of each ticker mentioned, and if currently in after hours, it will also list that price, if supported by the stock. Invalid tickers are ignored. Bot uses the IEX Cloud API to get stock information, which apparently allows for a couple hundreds requests a *second* on the free tier. I'll note that I do have an API token hardcoded in, but it's listed as a 'publishable' token which I take to mean that it doesn't matter if other people see it. idk it's probably terrible coding practice and if that's something that can't go in the master repo I can probably figure out a way to hide it. Screenshot of functionality included

Screen Shot 2021-02-24 at 9 44 45 PM

### CODE REVIEW

**Comment by CodeMastr3** [comment]
Gotta say this looks like a really cool feature

**Comment by Ramsfield** [comment]
This is really cool! We just moved to cogs, would you be willing to pull the new master and refactor this into an info cog?

**Comment by Ramsfield** [comment]
My only concern with this is the added overhead of sifting through every message any particular user would send.

Previous iterations of the bot will only react to `!` pre-pended commands, and not listen (or parse) to any other messages. What's the added overhead of the bot parsing this?

**Comment by Noxium** [comment]
I don't see this having a significant impact on the bot's performance during normal operation (ie. when stock tickers are not in a message). For any given message, it will perform regex to determine the presence of a stock ticker, and if none are found the function will return without sending any web requests. The added overhead should not be noticeable during operation. Not having a specific command attached to it was a conscious design decision, since I wanted usage to be seamless.

When tickers are found, it sends one request per ticker, which _is_ pretty slow (for the next iteration I may look into getting every ticker with one request). On my computer, it takes about 9.5 seconds to process the `max_tickers` (10) amount of tickers, during which time all other commands are blocked, although they will continue to process after the command is finished.

**Comment by CodeMastr3** [comment]
I do have to say we already have something watching and running code anytime a reaction is added or removed on a message

**Comment by Ramsfield** [comment]
@CodeMastr3 I was unaware of this. If that's the case then this shouldn't be any different.
I say pull it.

**Comment by CodeMastr3** [comment]
Well assuming this has been tested let's do it

**Pull request merged**
