### PR TITLE
Add QR code generation command

### PR DESCRIPTION
**Pull request by Asterisk007**

### CODE REVIEW

**Comment by CodeMastr3** [comment]
Questions. Can you give an example screenshot? And are you sure this is better in the funcog rather than the infocog?

**Comment by Asterisk007** [comment]
I can certainly move it to the infocog. Here's what a generated code looks like:
image

**Comment by Asterisk007** [comment]
I usually put new commands info funcog, but if you think it would better fit into infocog then so be it.

**Comment by CodeMastr3** [comment]
Not sure if intentional but the qr code has the "$qr" in it

**Comment by Asterisk007** [comment]
It's an earlier bug that has since been fixed.

**Comment by CodeMastr3** [comment]
Ah so that was an old screenshot then. Understood

**Comment by CodeMastr3** [comment]
Uhh I see that you removed the import discord from the funcog

**Comment by Asterisk007** [comment]
It doesn't seem to be used? VSCode shows it as grayed out.

**Comment by CodeMastr3** [comment]
I'm fairly certain it is okay to not have it.

**Pull request merged**
