### PR TITLE
Reenable changes to allow for .env file; Changes uwu command behavior

### PR DESCRIPTION
**Pull request by Asterisk007**

### CODE REVIEW

**Comment by Asterisk007** [comment]
Credit goes to #24

**Comment by Noxium** [comment]
Not my PR, but I'd like to contribute to the discussion since part of it concerns something I've written. I see this command getting regular use, so personally I'd like to see at least a couple other users to sign off on it before it leaves the server. As I've said, if @Asterisk007 can find 2 others that want this command gone then I'll be fine with it. Also if you want to add a user role that prevents the command being used against anyone in that role I'd also be fine with that. Hell it could even be enabled by default.

At the end of the day it's not my call, but that's my 2¢

**Comment by Asterisk007** [comment]
!uwu/!owo will now check if user has the role `uwu-immune`. If so, message will not be uwu'd.

**Comment by Axanimander** [comment]
I think this is a good change and should be applied.

**Comment by CodeMastr3** [comment]
I will be looking through every commit carefully then pull it when Dallas is ready to set up the env changes on the bots server else the bot will break

**Comment by Ramsfield** [comment]
I'm going to have to do some hands-on maintenance on the bot here soon. Assigning to myself and if @Noxium could check over the changes to !uwu to make sure he approves I would be ever grateful.

**Pull request merged**
